### ISSUE TITLE
initialize test for consistent acres-dwelling units 

### ISSUE THREAD

**Issue by mrspeel** [gregorbj/Archive-VisionEval#224]
One error that would be helpful to catch before runtime is noted below. Can this be added to an initialize module?

Ensure that if dwelling units >0 (VESimHouseholds/bzone_dwelling_units.csv),
unprotected acres (VELandUse/bzone_unprotected_area.csv)>0  
by Bzone.

**Comment by gregorbj** [comment]
Some changes to the framework software are needed to catch input errors like this. When the framework software loads inputs it only checks the values of the input files. Before adding the Initialize module capability, values could only be checked within individual input fields. Adding Initialize module capabilities added the ability to check between fields. In all cases, input file checks are not made against data that is in the datastore. Therefore, at most, you can only check between input files that are specified by modules within one package. You can't check consistency of inputs between packages (e.g. between VESimHouseholds and VELandUse). This could get even more limiting if we address another issue that has been raised because we can currently only have 1 Initialize module per package. This gets in the way of having different cross-field data checks for different models (RSPM & RPAT) that include modules in the same package. I think that in order to make checks between packages, the framework code will need to be changed to enable pulling data from the datastore so you can get the values that were input by modules in other packages. I don't think this is a trivial thing to do, but then again, it might not be as hard as I worry it would be.

**Comment by bstabler** [comment]
Moving issues here - https://github.com/VisionEval/VisionEval-Dev/issues
